### ISSUE TITLE
Курс Карпова

### ISSUE THREAD

**Issue by goosarararomama** [QuantumFluxx/karpov_courses#11]
Привет. Я тут только разбираюсь с гитхабом, вообще не алё, но надеюсь до вас доедет мой комментарий ^^
В "Знакомство с pandas" в "Практическом задании 2 урока" практика строится на работе с csv файлом с данными о поездках на такси.. И вот этого файла тама нет :( 
Попрактиковаться не получается. 
Я не знаю, может, и в последующих уроках тоже так будет, что практику можно только считывать уже готовую? 
В общем, если материалы для практики вдруг добавятся - будет мега-волшебно :3
И в любом случае спасибо огромное за курс!

**Comment by xclsv** [comment]
[2_taxi_nyc.csv](https://github.com/QuantumFluxx/karpov_courses/files/11224404/2_taxi_nyc.csv)
Не знаю, насколько он актуален, но он у меня есть )

**Comment by goosarararomama** [comment]
> [2_taxi_nyc.csv](https://github.com/QuantumFluxx/karpov_courses/files/11224404/2_taxi_nyc.csv) Не знаю, насколько он актуален, но он у меня есть )

Спасибонище!
